---
title: "Resultados modelo pronóstico"
date: "23/11/2021"
output:
  html_document:
    df_print: paged
    mode: selfcontained
params:
  p_esc: tendencial
  p_region: r2
  p_nombre_taller: Integrado
  p_time: !r c('0', '5', '10', '15', '20', '25')
  p_vars: !r c('TUNT', 'TUSP', 'HUMT', 'VACUI', 'BMAT')
  p_version: v3
  #p_vars: !r c('AGR','AGRQ', 'MIEL', 'MMAYA', 'CFOR', 'HABT', 'CCO2', 'GEI', 'RECAR', 'URB')
  p_conf_level: 0.95
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
mean_cl_quantile <- function(x, q = c(0.1, 0.9), na.rm = TRUE){
  dat <- data.frame(y = mean(x, na.rm = na.rm),
                    ymin = quantile(x, probs = q[1], na.rm = na.rm),
                    ymax = quantile(x, probs = q[2], na.rm = na.rm))
  return(dat)
}
```

```{r include=FALSE}
graficar <- function(data_summary, data_t, xtime, titulo){
  out <- ggplot(data_summary, aes(x = t, y = Media)) +
  
#### plot individual measurements ####
	geom_line(data=data_t, aes(x = t, y = Estado, group = Experimento, color= Experimento)) +

#### plot error (95%CI) of the response over time ####
	geom_ribbon(data=data_summary, aes(ymin=CI_lower, ymax=CI_upper) ,fill="gray", alpha=0.7)+
    
#### plot average response over time ####
	geom_line(data=data_summary, aes(x = t, y = Media), size=1, alpha=0.5, color = "black")+

#### Draw a filled, transparent rectangle to indicte when stimulation takes place
	#annotate("rect", xmin=stim_start, xmax=stim_end, ymin=-Inf, ymax=Inf, alpha=0.1, fill="black")+

## Set the Y-axis scale, remove for autoscale
	coord_cartesian(xlim = c(0, xtime), ylim = c(0,1)) +
  
## Set theme&basic font
	theme_light(base_size = 16) #+
  
### Style the axis (font size)
	# theme(axis.text.x = element_text(size=16, angle=0, vjust = 0), axis.text.y = element_text(size=16)) +

### Set layout of the graph 
	theme(panel.border = element_rect(size = 1, linetype = "solid", colour = "black", fill=NA)) +

### Set aspect ratio of the graph n/n = square
	#theme(aspect.ratio=4/4)
  return(out + labs(x= "Tiempo (años)", y = "Valor", title = titulo) + theme(legend.position="none"))
}
```

```{r include=FALSE}
datos_summ <- function(x){
df_summary <- x %>% group_by(t) %>% 
        summarise(Media = mean(Estado, na.rm = TRUE),
    							sd = sd(Estado, na.rm = TRUE),
    							n = n()) %>%
  		            mutate(sem = sd / sqrt(n - 1),
                  CI_lower = Media + qt((1-Conf_level)/2, n - 1) * sem,
                  CI_upper = Media - qt((1-Conf_level)/2, n - 1) * sem)
return(df_summary)
}
```

```{r include=FALSE}
clean_data_exp <- function(x){
  data_tidy <- gather(x, t, Estado, -Experimento)
  data_tidy$t <- as.numeric(as.character(data_tidy$t))
  return(data_tidy)
}
```

```{r include=FALSE}
extraer_variable <- function(x, variable, par_val, first_column_name){
  tmp <- x %>%
    select(starts_with(par_val) | starts_with(variable))
  tmp <- tmp[,1:7]
  names(tmp) <- c(first_column_name, time_values)
  return(tmp)
}
```

```{r include=FALSE}
calcular_rango <- function(y){
  x <- (round(max(y$`0`),1)-round(min(y$`0`),1))/4
  rango <- seq(round(min(y$`0`),1), round(max(y$`0`),1), by = x)
  return(round(rango, 2))
}
```


```{r include=FALSE}
intervalos <- function(y, rango){
  cortes <- list()
  for (i in 1:4) {
    if (i == 1) {
      cortes[[i]] <- filter(y, `0`>= rango[1] & `0`< rango[2])  
    }
    else if (i == 2){
      cortes[[i]] <- filter(y, `0`>= rango[2] & `0`< rango[3])
    }
    else if (i==3){
      cortes[[i]] <- filter(y, `0`>= rango[3] & `0`< rango[4])
    }
    else{
      cortes[[i]] <- filter(y, `0`>= rango[4])
    }
    cortes[[i]] <- clean_data_exp(cortes[[i]])
    
  }
  return(cortes)
}
```

```{r include=FALSE}
intervalos_est <- function(x){
  data_est_cortes <- list()
  for (i in 1:4){
    data_est_cortes[[i]] <- datos_summ(x[[i]])  
  }
  return(data_est_cortes)
}
```

```{r include=FALSE}
graficar_media <- function(data_s, xtime, titulo){
  out <- ggplot(data_s, aes(x = t, y = Estado, group = Variable, color= Variable)) +
    
  ##geom_line() +
  
  geom_smooth(se=FALSE) +
## Set the Y-axis scale, remove for autoscale
	coord_cartesian(xlim = c(0, xtime), ylim = c(0,1)) +
  
## Set theme&basic font
	theme_light(base_size = 16) #+
  
### Style the axis (font size)
	# theme(axis.text.x = element_text(size=16, angle=0, vjust = 0), axis.text.y = element_text(size=16)) +

### Set layout of the graph 
	#theme(panel.border = element_rect(size = 1, linetype = "solid", colour = "black", fill=NA)) +


 theme(legend.key=element_blank(), legend.background=element_blank()) +


### Set aspect ratio of the graph n/n = square
	#theme(aspect.ratio=4/4)
  return(out + labs(x= "Tiempo (años)", y = "Valor", title = titulo))
}
```

```{r include=FALSE}
region_folder <- function(x){
  case_when(
  x == "r1" ~ "region_1",
  x == "r2" ~ "region_2",
  x == "r3" ~ "region_3",
  x == "r4" ~ "region_4",
  x == "r5" ~ "region_5",
  x == "r6" ~ "region_6",
  x == "r7" ~ "region_7",
)
}
```

```{r include=FALSE}
region_name <- function(x){
  case_when(
  x == "r1" ~ "Region 1",
  x == "r2" ~ "Region 2",
  x == "r3" ~ "Region 3",
  x == "r4" ~ "Region 4",
  x == "r5" ~ "Region 5",
  x == "r6" ~ "Region 6",
  x == "r7" ~ "Region 7",
)
}
```


```{r include=FALSE}
#install.packages("readxl")
library(readxl)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(tidyverse)
library(maditr)
```


# Modelo: `r params$p_nombre_taller` (`r params$p_esc`)
```{r include=FALSE}
escenario <- params$p_esc
region <- params$p_region
version <- params$p_version

ruta_in <- paste0("C:/Dropbox (LANCIS)/CARPETAS_TRABAJO/apc_temeraria/pronostico/scenarios/", region_folder(region), "/", escenario, "_", region, "_", version, "/banco.xlsx")

# Experimentos
data <- read_excel(ruta_in, sheet = "Datos1")

# Estadísticas
data_est <- read_excel(ruta_in, sheet = "Datos")

# Diccionario
diccionario <- read.csv("./insumos/diccionario_abrev.csv", fileEncoding = "UTF-8", check.names=F)
data_est <- data_est[-c(15,16), ]
```


```{r, include=FALSE}
Conf_level <-  params$p_conf_level
variables <- params$p_vars
time_values <- as.numeric(params$p_time)
n <- nrow(data)
toggle <-  c(rep(TRUE, length(variables)), rep(FALSE, 20-length(variables)))

# Extraer variables
data_tmp <- list()
data_est_tmp <- list()
for (i in 1:length(variables)) {
  data_tmp[[i]] <- extraer_variable(data, variables[i], 'Val', 'Experimento')
  data_est_tmp[[i]] <- extraer_variable(data_est, variables[i], 'Est', 'Estadisticas')
}
```

```{r warning=FALSE, include=FALSE}
# formato df
data_tidy <- list()
for (i in 1:length(variables)) {
  data_tidy[[i]] <- gather(data_tmp[[i]], t, Estado, -Experimento)
  data_tidy[[i]]$t <- as.numeric(as.character(data_tidy[[i]]$t))
}

est_tidy <- list()
for (i in 1:length(variables)) {
  est_tidy[[i]] <- gather(data_est_tmp[[i]], t, Valor, -Estadisticas)
  est_tidy[[i]]$t = as.numeric(as.character(est_tidy[[i]]$t))
  est_tidy[[i]]$Valor = as.numeric(as.character(est_tidy[[i]]$Valor))
  est_tidy[[i]] <- dcast(data = est_tidy[[i]],formula = t~Estadisticas)
  est_tidy[[i]]$sem <- est_tidy[[i]]$`Desviación estándar`/sqrt(n-1)
  est_tidy[[i]]$CI_lower <- est_tidy[[i]]$Media + qt((1-Conf_level)/2, df=n-1)*est_tidy[[i]]$sem
  est_tidy[[i]]$CI_upper <- est_tidy[[i]]$Media - qt((1-Conf_level)/2, df=n-1)*est_tidy[[i]]$sem
} 
```

```{r include=FALSE}
# cortes para cada variable
data_cortes <- list()
rango_list <- list()
data_cortes_est <- list()
for (i in 1:length(variables)) {
  rango_list[[i]] <- calcular_rango(data_tmp[[i]])
  data_cortes[[i]] <- intervalos(data_tmp[[i]], rango_list[[i]])
  # calcular la estadística para los cortes
  data_cortes_est[[i]] <- intervalos_est(data_cortes[[i]])
}
tmp <- 1
```

```{r warning=FALSE, include=FALSE}
x <- rbind(est_tidy[[1]]$Media, est_tidy[[2]]$Media)
for (i in 3:length(est_tidy)) {
  x <- rbind(x, est_tidy[[i]]$Media)
}
colnames(x) <- time_values
x <- as.data.frame(x)
x$Variable <- variables
datat <- gather(x, t, Estado, -Variable)
datat$t <- as.numeric(as.character(datat$t))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
graficar_media(datat, xtime=max(time_values), titulo = "Media")
```


## `r variables[tmp]`-`r diccionario$desc[diccionario$variable == variables[tmp]]`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```

```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 2
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 3
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 4
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 5
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 6
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 7
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 8
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 9
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 10
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 11
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 12
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 13
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 14
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 15
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 16
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 17
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 18
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 19
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```

## `r etiqueta`
```{r echo=FALSE, eval= toggle[tmp]}
rfull <- paste0("(", round(min(data_tmp[[tmp]]$`0`),1), "," ,round(max(data_tmp[[tmp]]$`0`),1),")")
graficar(est_tidy[[tmp]], data_tidy[[tmp]], xtime=max(time_values), titulo = rfull)
```
```{r echo=FALSE, eval= toggle[tmp]}
r1 <- paste0("(", rango_list[[tmp]][1], ",", rango_list[[tmp]][2], "]")
r2 <- paste0("(", rango_list[[tmp]][2], "," ,rango_list[[tmp]][3],"]")
r3 <- paste0("(", rango_list[[tmp]][3], "," ,rango_list[[tmp]][4],"]")
r4 <- paste0("(", rango_list[[tmp]][4], "," ,rango_list[[tmp]][5],")")
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[1]], data_cortes[[tmp]][[1]], xtime=max(time_values), titulo = r1),
                  graficar(data_cortes_est[[tmp]][[2]], data_cortes[[tmp]][[2]], xtime=max(time_values), titulo = r2))
```
```{r echo=FALSE, eval= toggle[tmp]}
ggpubr::ggarrange(graficar(data_cortes_est[[tmp]][[3]], data_cortes[[tmp]][[3]], xtime=max(time_values), titulo = r3),
                  graficar(data_cortes_est[[tmp]][[4]], data_cortes[[tmp]][[4]], xtime=max(time_values), titulo = r4))
tmp <- 20
if (toggle[tmp] == TRUE) {
  etiqueta = paste0(variables[tmp], "-", diccionario$desc[diccionario$variable == variables[tmp]])
  } else {
  etiqueta = ""
}
```